Switch to hypridle and hyprlock

diff --git a/nvimpager-wrapper b/nvimpager-wrapper
--- a/nvimpager-wrapper
+++ b/nvimpager-wrapper
@@ -1,14 +1,15 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
 args="${@:1}"
 
-if command -v /usr/bin/nvimpager >/dev/null; then
-    NVIMPAGER=/usr/bin/nvimpager
-elif command -v /usr/local/bin/nvimpager > /dev/null; then
-    NVIMPAGER=/usr/local/bin/nvimpager
-else
-    echo "'nvimpager' not found in path"
-    exit 1
-fi
+# if command -v /usr/bin/nvimpager >/dev/null; then
+#     NVIMPAGER=/usr/bin/nvimpager
+# elif command -v /usr/local/bin/nvimpager > /dev/null; then
+#     NVIMPAGER=/usr/local/bin/nvimpager
+# else
+#     echo "'nvimpager' not found in path"
+#     exit 1
+# fi
 
-$NVIMPAGER $args -p <&0
+# $NVIMPAGER $args -p <&0
+command nvimpager $args -p <&0
