Support nvimpager-wrapper on mac

diff --git a/nvimpager-wrapper b/nvimpager-wrapper
--- a/nvimpager-wrapper
+++ b/nvimpager-wrapper
@@ -2,4 +2,13 @@
 
 args="${@:1}"
 
-/usr/bin/nvimpager $args -p <&0
+if command -v /usr/bin/nvimpager >/dev/null; then
+    NVIMPAGER=/usr/bin/nvimpager
+elif command -v /usr/local/bin/nvimpager > /dev/null; then
+    NVIMPAGER=/usr/local/bin/nvimpager
+else
+    echo "'nvimpager' not found in path"
+    exit 1
+fi
+
+$NVIMPAGER $args -p <&0
